In [1]:
import torch
import torchvision

In [2]:
# cuda helps in computations in GPU
print(torch.cuda.is_available())

False


In [3]:
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [4]:
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [5]:
print(a.shape)
print(b.shape)

torch.Size([3])
torch.Size([4, 3])


In [6]:
print(b.shape[0])

4


In [7]:
## FloatTensor
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
## DoubleTensor
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [9]:
print(c.dtype)

torch.float32


In [10]:
print(c.mean())
print(d.std())

tensor(2.5833)
tensor(1.5050, dtype=torch.float64)


In [12]:
## Reshaping the tensor
print(b.view(-1,1))
print(b.view(12))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])


In [13]:
# 3d (channels,rows,columns)
torch.randn(2,3,4)

tensor([[[ 1.6162e+00, -1.4973e-01,  1.2580e+00, -2.0297e+00],
         [ 1.0678e-03,  7.3487e-01, -5.3054e-01,  1.7657e-01],
         [ 1.0682e-01,  1.4237e+00, -3.0932e-01, -1.1437e+00]],

        [[-4.1511e-01, -2.1322e+00, -6.1320e-02,  1.2995e+00],
         [ 4.0906e-01, -4.1154e-01,  4.0087e-01,  6.2385e-01],
         [-1.2920e-01,  2.6247e-01, -1.0780e+00, -4.0105e-01]]])

In [14]:
## select random number from a norman distrubition
torch.randn(4,4)

tensor([[ 0.2576, -0.8461,  0.1260, -0.9063],
        [ 1.3810, -0.4394,  1.0355, -0.6895],
        [ 1.5317, -1.7166,  0.1363,  0.9746],
        [ 0.3850,  0.0518,  0.5253,  0.5034]])

In [15]:
# total number of elements in a tensor
torch.numel(c)

12

In [16]:
## to add tensor they need to be of same shape and size

torch.add(c,d)

## inplace addition
c.add_(d)
# _ represents inplace addition.

tensor([[ 4.,  2.,  8.],
        [ 6., 10.,  8.],
        [ 2.,  4.,  0.],
        [ 8.,  6.,  4.]], dtype=torch.float64)

In [ ]:
# Numpy Bridge

In [17]:
# converting torch tensor to numpy array.

a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])